// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcogEXb-NdSznNvgcHVdcYD5-u_04-XWE',
    appId: '1:1096867473222:android:8b55c0f1573aeb15dbe747',
    messagingSenderId: '1096867473222',
    projectId: 'dodream-87de4',
    storageBucket: 'dodream-87de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiacl5I894j6Av4N9E0l_7kV4Ary5dVQQ',
    appId: '1:1096867473222:ios:848b157f8ad7ceb2dbe747',
    messagingSenderId: '1096867473222',
    projectId: 'dodream-87de4',
    storageBucket: 'dodream-87de4.firebasestorage.app',
    iosBundleId: 'com.dodream.doDream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9JmS6iVZkq6lritXbl67j8x1_En8gC2k',
    appId: '1:1096867473222:web:1849c848588d6849dbe747',
    messagingSenderId: '1096867473222',
    projectId: 'dodream-87de4',
    authDomain: 'dodream-87de4.firebaseapp.com',
    storageBucket: 'dodream-87de4.firebasestorage.app',
  );
}
